// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace IdleTalks.DA
{
    // Conversation
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.0.0")]
    public class Conversation
    {
        public Guid Id { get; set; } // Id (Primary key via unique index PK_Conversation_Id)
        public long UserOneId { get; set; } // UserOneId
        public long UserTwoId { get; set; } // UserTwoId

        // Reverse navigation
        public virtual ICollection<ConversationReply> ConversationReplies { get; set; } // ConversationReply.FK_ConversationReply_Conversation

        // Foreign keys
        public virtual User User_UserOneId { get; set; } // FK_Conversation_UserOne
        public virtual User User_UserTwoId { get; set; } // FK_Conversation_UserTwo
        
        public Conversation()
        {
            Id = System.Guid.NewGuid();
            ConversationReplies = new List<ConversationReply>();
        }
    }

}
// </auto-generated>
