// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace IdleTalks.DA
{
    // ConversationReply
    public class ConversationReplyConfiguration : EntityTypeConfiguration<ConversationReply>
    {
        public ConversationReplyConfiguration()
            : this("dbo")
        {
        }
 
        public ConversationReplyConfiguration(string schema)
        {
            ToTable(schema + ".ConversationReply");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("Id").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.ConversationId).HasColumnName("ConversationId").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.UserId).HasColumnName("UserId").IsRequired().HasColumnType("bigint");
            Property(x => x.Message).HasColumnName("Message").IsRequired().HasColumnType("nvarchar").HasMaxLength(1024);

            // Foreign keys
            HasRequired(a => a.Conversation).WithMany(b => b.ConversationReplies).HasForeignKey(c => c.ConversationId); // FK_ConversationReply_Conversation
        }
    }

}
// </auto-generated>
