// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace IdleTalks.DA
{
    // ConversationReply
    public class ConversationReply
    {
        public Guid Id { get; set; } // Id (Primary key via unique index PK_ConversationReply_Id)
        public Guid ConversationId { get; set; } // ConversationId
        public long UserId { get; set; } // UserId
        public string Message { get; set; } // Message

        // Foreign keys
        public virtual Conversation Conversation { get; set; } // FK_ConversationReply_Conversation
        
        public ConversationReply()
        {
            Id = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
