// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace IdleTalks.DA
{
    // Conversation
    public class ConversationConfiguration : EntityTypeConfiguration<Conversation>
    {
        public ConversationConfiguration()
            : this("dbo")
        {
        }
 
        public ConversationConfiguration(string schema)
        {
            ToTable(schema + ".Conversation");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("Id").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.UserOneId).HasColumnName("UserOneId").IsRequired().HasColumnType("bigint");
            Property(x => x.UserTwoId).HasColumnName("UserTwoId").IsRequired().HasColumnType("bigint");

            // Foreign keys
            HasRequired(a => a.User_UserOneId).WithMany(b => b.Conversations_UserOneId).HasForeignKey(c => c.UserOneId); // FK_Conversation_UserOne
            HasRequired(a => a.User_UserTwoId).WithMany(b => b.Conversations_UserTwoId).HasForeignKey(c => c.UserTwoId); // FK_Conversation_UserTwo
        }
    }

}
// </auto-generated>
