// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace IdleTalks.DA
{
    // Mood
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.0.0")]
    public class Mood
    {
        public long Id { get; set; } // Id (Primary key via unique index PK_Mood_Id)
        public long UserId { get; set; } // UserId
        public string Text { get; set; } // Text

        // Reverse navigation
        public virtual ICollection<User> Users { get; set; } // User.FK_User_Mood

        // Foreign keys
        public virtual User User { get; set; } // FK_Mood_User
        
        public Mood()
        {
            Users = new List<User>();
        }
    }

}
// </auto-generated>
